#!/bin/sh

if [ -x "/etc/init.d/nginx" ]; then
    update-rc.d nginx defaults >/dev/null
    if [ -e /var/run/nginx.pid ]; then 
        echo "nginx is running, restarting...";         
        /etc/init.d/nginx restart
    else
        /etc/init.d/nginx start
    fi
fi
